export const CONFERENCES = [
  {
    title:
      'Interfaces vs wild: Building safer interfaces with TypeScript and Functional Programming',
    for: 'Wey Wey Web',
    type: 'talk',
    year: '2022',
    place: 'Málaga',
    language: 'EN',
    youtube: 'yLgIDFeeufA',
  },
  {
    title: 'Esta charla es una "monada". Introducción a FP en JavaScript con Ramda',
    for: 'JSDay Canarias',
    type: 'talk',
    year: '2019',
    place: 'San Cristóbal de la Laguna (Tenerife)',
    language: 'ES',
    youtube: 'YJvTlB1-MVI',
  },
  {
    title: 'App con Next.JS y Chakra UI',
    for: 'Geekshub',
    type: 'talk',
    year: '2021',
    place: 'Online',
    language: 'ES',
    youtube: '1zpu5WwPphs',
  },
  {
    title: 'Patrones comunes de React con TypeScript',
    for: 'Geekshub',
    type: 'talk',
    year: '2020',
    place: 'Online',
    language: 'ES',
    youtube: 'fZ0Z5xmm3QU',
  },
  {
    title: 'Una historia de testing efectivo en JavaScript',
    for: 'MurciaDev',
    type: 'talk',
    year: '2019',
    place: 'Murcia',
    language: 'ES',
  },
  {
    title:
      'Construyendo un sistema de diseño en React con Styled Components, Styled System y Storybook',
    for: 'JSDay Canarias',
    type: 'workshop',
    year: '2018',
    place: 'San Cristóbal de la Laguna (Tenerife)',
    language: 'ES',
  },
  {
    title: 'A living design system with React Storybook',
    for: 'React Alicante',
    type: 'workshop',
    year: '2018',
    place: 'Alicante',
    language: 'EN',
  },
  {
    title: 'Iniciación al desarrollo PHP con el Framework CodeIgniter',
    for: 'Asociación de Desarrolladores Web de España',
    type: 'talk',
    year: '2011',
    place: 'Murcia',
    language: 'ES',
  },
];